image: docker:20.10.16

services:
  - docker:20.10.16-dind

variables:
  CI_REGISTRY_IMAGE: devops.telecomste.fr:5050/printerfaceadmin/2022-23/group6
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""


before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

stages:
  - build
  - test
  - lint

build:
  stage: build
  script:
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA --tag $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE:latest

test_loadConfiguration:
  stage: test
  script:
    - python3 -m unittest tests/test_loadConfiguration.py

#test_connexion:
#  stage: test
#  before_script:
#    - pip install paramiko
#  script:
#    - python3 -m unittest tests/test_connexion.py

test_apacheLogParser:
  stage: test
  script:
    - python3 -m unittest tests/test_apacheLogParser.py

test_apacheLogInfo:
  stage: test
  script: 
    - python3 -m unittest tests/test_apacheLogInfo.py

#linter:
#  stage: lint
#  before_script:
#    - pip install pylint
#  script:
#    - pylint $PROJECT_ROOT







