# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Python.gitlab-ci.yml

stages:
  - test

# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: http://devops.telecomste.fr:5050/printerfaceadmin/2022-23/group6:python-docker-test

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  TEST_DIR: "$CI_PROJECT_DIR/tests"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/topics/caching/
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python --version  # For debugging
  - virtualenv venv
  - source venv/bin/activate

test_loadConfiguration:
  stage: test
  script:
    - python3 -m unittest tests/test_loadConfiguration.py

#test_connexion:
#  stage: test
#  before_script:
#    - pip install paramiko
#  script:
#    - python3 -m unittest tests/test_connexion.py

test_apacheLogParser:
  stage: test
  script:
    - python3 -m unittest tests/test_apacheLogParser.py

test_apacheLogInfo:
  stage: test
  script: 
    - python3 -m unittest tests/test_apacheLogInfo.py






