# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Python.gitlab-ci.yml

stages:
  - build
  - test
  - lint

build:
  image: docker:20.10.16
  stage: build
  services:
    - docker:20.10.16-dind
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  script:
    - apk add --no-cache bash python3
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

image: devops.telecomste.fr:5050/printerfaceadmin/2022-23/group6:python-docker-test

test_loadConfiguration:
  stage: test
  script:
    - python3 -m unittest tests/test_loadConfiguration.py

#test_connexion:
#  stage: test
#  before_script:
#    - pip install paramiko
#  script:
#    - python3 -m unittest tests/test_connexion.py

test_apacheLogParser:
  stage: test
  script:
    - python3 -m unittest tests/test_apacheLogParser.py

test_apacheLogInfo:
  stage: test
  script: 
    - python3 -m unittest tests/test_apacheLogInfo.py

#linter:
#  stage: lint
#  before_script:
#    - pip install pylint
#  script:
#    - pylint $PROJECT_ROOT






