image: docker:20.10.16

variables:
  CI_REGISTRY_IMAGE: devops.telecomste.fr:5050/printerfaceadmin/2022-23/group6

services:
  - name: docker:dind
    entrypoint: ["env", "-u", "DOCKER_HOST"]
    command: ["dockerd-entrypoint.sh"]

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

stages:
  - build
  - test
  - lint

build:
  stage: build
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"

test_loadConfiguration:
  stage: test
  script:
    - python3 -m unittest tests/test_loadConfiguration.py

#test_connexion:
#  stage: test
#  before_script:
#    - pip install paramiko
#  script:
#    - python3 -m unittest tests/test_connexion.py

test_apacheLogParser:
  stage: test
  script:
    - python3 -m unittest tests/test_apacheLogParser.py

test_apacheLogInfo:
  stage: test
  script: 
    - python3 -m unittest tests/test_apacheLogInfo.py

#linter:
#  stage: lint
#  before_script:
#    - pip install pylint
#  script:
#    - pylint $PROJECT_ROOT







